CREATE DATABASE Config_Console
USE Config_Console
use lab01
DROP DATABASE Config_Console

CREATE TABLE HS_CONFIG_CLIENT(
SUB_DOMAIN varchar(200) PRIMARY KEY,
SERVER_NAME varchar(50),
DATABASE_NAME varchar(20),
USERNAME varchar(50),
PSW varchar(30)
);

CREATE TABLE HS_CONFIG_USER(
USER_KEY varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_USER_LOGIN(USL_ID) PRIMARY KEY,
USER_NAME varchar(100),
USER_DISPLAY_NAME varchar(100),
USER_STATUS varchar(10),
USER_TIME_STAMP time,
USER_UPDATE_TIME time,
SYS_CAPABILITY_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_SYS_CAPABILITY(SYS_CAPABILITY_ID),
PRO_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_PROFILE(PRO_ID)
);

CREATE TABLE HS_CONFIG_SYS_CAPABILITY(
SYS_CAPABILITY_ID varchar(20) PRIMARY KEY,
SYS_CAPABILITY_NAME varchar(100),
);

CREATE TABLE HS_CONFIG_SYS_CAP_MATRIX(
MATRIX_ID varchar(20) PRIMARY KEY,
ACTION varchar(100),
ACCESS_RIGHT varchar(20),
SYS_CAPABILITY_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_SYS_CAPABILITY(SYS_CAPABILITY_ID)
);

CREATE TABLE HS_CONFIG_PROFILE(
PRO_ID varchar(20) PRIMARY KEY,
PRO_FIRST_NAME varchar(50),
PRO_LAST_NAME varchar(50),
PRO_EMAIL varchar(50),
PRO_TITLE varchar(20),
PRO_TIME_STAMP time,
PRO_BIRTHDAY date,
PRO_GENDER varchar(20),
PRO_TELE int,
PRO_MOBILE int,
PRO__JOINED_DATE date,
PRO_STATUS varchar(10),
PRO_DESCRIPTION varchar(100),
PRO_UPDATED_TIME time,
PRO_DEPARTMENT varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_DEPARTMENT(DEP_ID),
PRO_DESIGNATION varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_DESIGNATION(DESIG_ID)
);

CREATE TABLE HS_CONFIG_USER_LOGIN(
USL_ID varchar(20) PRIMARY KEY,
USL_PROVIDER varchar(50),
USL_PASSWORD varchar(30),
USL_STATUS varchar(10),
USL_UPDATEDATE date,
USER_KEY varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_USER(USER_KEY)
);

CREATE TABLE HS_CONFIG_LOG_HISTORY(
LOG_ID varchar(20) PRIMARY KEY,
LOG_TIME datetime,
ACTION varchar(100),
DESCRIPTION varchar(100),
CHANGE_OLD varchar(20),
CHANGE_NEW varchar(20),
USL_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_USER_LOGIN(USL_ID),
PRO_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_PROFILE(PRO_ID)
);

CREATE TABLE HS_CONFIG_DEPARTMENT(
DEP_ID varchar(20) PRIMARY KEY,
DEP_NAME varchar(50)
);

CREATE TABLE HS_CONFIG_DESIGNATION(
DESIG_ID varchar(20) PRIMARY KEY,
DESIG_NAME varchar(50)
);

CREATE TABLE HS_CONFIG_REPORTTO(
ID varchar(20),
SUP_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_PROFILE(PRO_ID),
PROF_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_PROFILE(PRO_ID)
);

CREATE TABLE HS_CONFIG_ASSIGNMENT(
ID varchar(20) PRIMARY KEY,
CLIENT_HOST_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_HOST(CLIENT_ID),
PRO_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_PROFILE(PRO_ID),
FEA_CAPABILITY_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_FEATURE_CAPABILITY(FEA_CAPABILITY_ID)
);

CREATE TABLE HS_CONFIG_FEATURE_CAPABILITY(
FEA_CAPABILITY_ID varchar(20) PRIMARY KEY,
FEA_CAPABILITY_NAME varchar(50)
);

CREATE TABLE HS_CONFIG_FEATURE_MATRIX(
MATRIX_ID varchar(20) PRIMARY KEY,
TASK varchar(100),
ACCESS_RIGHT varchar(20),
FEA_CAPABILITY_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_FEATURE_CAPABILITY(FEA_CAPABILITY_ID)
);

CREATE TABLE HS_CONFIG_HOST_ATTACHMENT(
ATT_ID varchar(20) PRIMARY KEY,
ATT_TYPE varchar(10),
FILE_NAME varchar(20),
BINARY varchar(10),
CLIENT_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_CLIENT_HOST(CLIENT_HOST_ID),
SERVER_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_FEATURE_HOST_SERVER(SERVER_ID)
);

CREATE TABLE HS_CONFIG_CLIENT_HOST(
CLIENT_HOST_ID varchar(20) PRIMARY KEY,
NAME varchar(50),
--APP_SERVER_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_HOST_SERVER(CLIENT_HOST_ID),
--DB_SERVER_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_HOST_SERVER(CLIENT_HOST_ID),
--SERVICE_SERVER_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_HOST_SERVER(CLIENT_HOST_ID),
--IS_SAAS varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_HOST_SERVER(CLIENT_HOST_ID),
SAAS_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_CLIENT_HOST_SAAS(SAAS_ID)
);

CREATE TABLE HS_CONFIG_CLIENT_HOST_SAAS(
SAAS_ID varchar(20) PRIMARY KEY,
MAIN_DB_SERVER varchar(20),
MAIN_DB_NAME varchar(20),
MAIN_DB_USER_ID varchar(20),
MAIN_DB_PWD varchar(20),
MAIN_DB_SCHEMA varchar(20)
);

CREATE TABLE HS_CONFIG_CLIENT_HOST_IMAGE(
ID varchar(20) PRIMARY KEY,
PICTURE varchar(20),
FILE_NAME varchar(20)
);

CREATE TABLE HS_CONFIG_CLIENT_SERVICE(
ID varchar(20),
CLIENT_HOST_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_CLIENT_HOST(CLIENT_HOST_ID),
SERVICE_NAME varchar(50)
);

CREATE TABLE HS_CONFIG_HOST_SERVER(
SERVER_ID varchar(20) PRIMARY KEY,
CLIENT_HOST_ID varchar(20) FOREIGN KEY REFERENCES HS_CONFIG_CLIENT_HOST(CLIENT_HOST_ID),
SERVER_TYPE varchar(20),
LOCATION varchar(20),
IP_ADDRESS varchar(20),
DNS_NAME varchar(50),
PORT varchar(20),
LOG_FOLDER_PATH varchar(50),
REPORT_PATH varchar(50),
JS_PATH varchar(50),
SAAS_CLIENT_ID varchar(20),
DB_SEREVER_NAME varchar(20),
DB_NAME varchar(20),
DB_USER_ID varchar(20),
DB_PWD varchar(30),
DB_SCHEMA varchar(20)
);